### ISSUE TITLE
Remote profiler not working.

### ISSUE THREAD

**Issue by kkukielka** [meteorhacks/kadira-profiler#4]
Hey!

I have added package for profiling my meteor app, and after running:

```
Kadira.profileCpu(10, "ID_FROM_PROFILER_SITE", "remote");
```

I got exception:

```
Kadira: CPU profiling attempt failed: Internal server error [500]
```

And on server side:

```
Exception while invoking method 'kadira.profileCpu' {
stack: 'TypeError: Cannot call method \'getJob\' of undefined
    at Object.Jobs.getAsync (packages/meteorhacks_kadira/lib/jobs.js:4:1)
    at Object.get (packages/meteor/helpers.js:118:1)
    at remoteProfileCPU (packages/meteorhacks_kadira-profiler/lib/server.js:17:1)
    at [object Object].Meteor.methods.kadira.profileCpu (packages/meteorhacks_kadira-profiler/lib/server.js:8:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/Users/chris/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/chris/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
    at new Promise (/Users/chris/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
    at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
    at packages/meteorhacks_kadira/lib/hijack/wrap_session.js:52:1',source: 'method' }
```

I am using meteor@1.2.1 and I have updated all kadira packages. 

Running `Kadira.profileCpu(10)` works and saves file to /tmp

All kadira packages are added to project packages.

What am I doing wrong? :( Thx for any help!

**Comment by arunoda** [comment]
Could you update `meteorhacks:kadira` to the latest version.
It is `v2.27.3.`

**Comment by kkukielka** [comment]
I already did:
![screen shot 2016-01-28 at 13 54 01](https://cloud.githubusercontent.com/assets/2983580/12644919/a48ba17e-c5c6-11e5-8711-99556583371a.png)

**Comment by arunoda** [comment]
Okay. To do that, you need to connect to Kadira. Are you?

**Comment by kkukielka** [comment]
Yes, we have premium account for our deployments, and I just wanted to check CPU profile. Kadira works perfectly :)

**Comment by arunoda** [comment]
This error happens when your app not connected to Kadira. Check whether this app has `Kadira: Successfully connected` in the logs.

**Comment by kkukielka** [comment]
Ok, I have a new error on ui.kadira.io:

![zrzut ekranu 2016-02-01 o 17 06 05](https://cloud.githubusercontent.com/assets/2983580/12722716/757db7da-c906-11e5-946c-b7a2bfe6ccf3.png)

Node didn't register module? 

I am working on node `v0.12.9` right now.

**Comment by arunoda** [comment]
@kkukielka Meteor doesn't work with v0.12.9 but with 0.10.x.
And our profiler is built for 0.10.x.
So use it.

**Comment by kkukielka** [comment]
Oh ok! Great! Now I know what I have to do :) Thank you!

**Comment by arunoda** [comment]
Reopen if that's not solve your problem.
