### ISSUE TITLE
Error: Cannot find module '../'

### ISSUE THREAD

**Issue by gsabran** [meteorhacks/kadira-profiler#6]
I've upgraded to meteor 1.4 and deploying with kadirahq/mup now throws an error. If I removed kadira-profiler things works fine. I reported the issue [here](https://github.com/kadirahq/meteor-up/issues/275) originally, but it seems to be more related to the profiler.

The error is

```
Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/meteorhacks_kadira-binary-deps/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by cesarve77** [comment]
I have the same issue. But I'm not using kadira-profiler

here my packages:

```
accounts-facebook                1.0.10  Login service for Facebook accounts
accounts-google                  1.0.10  Login service for Google accounts
accounts-password                1.3.0  Password support for accounts
alanning:roles                   1.2.15  Authorization package for Meteor
aldeed:autoform                  5.8.1+ Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:autoform-select2          2.0.2  Custom select2 input type for AutoForm
aldeed:simple-schema             1.5.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
andrei:autoform-raty             0.0.1  AutoForm input type for Raty, a jQuery star rating form control
arillo:flow-router-helpers       0.5.2  Template helpers for flow-router
blaze-html-templates             1.0.5  Compile HTML templates into reactive UI with Meteor Blaze
cesarve:bs-modal-prompt          0.1.0+ Show prompts in a bootstrap modal.
dispatch:login-token             0.1.2+ Log the user in if they have the correct single-use token in the URL
ecmascript                       0.5.8_1  Compiler plugin that supports ES2015+ in all .js files
email                            1.1.17_1  Send email messages
es5-shim                         4.6.14_1  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome          4.6.3  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
http                             1.2.9_1  Make HTTP calls to remote servers
jquery                           1.11.9  Manipulate the DOM using CSS selectors
kadira:blaze-layout              2.3.0  Layout Manager for Blaze (works well with FlowRouter)
kadira:debug                     3.2.2  Full Stack Debugging Solution for Meteor
kadira:flow-router               2.12.1  Carefully Designed Client Side Router for Meteor
less                             2.7.5_1  Leaner CSS language
lukemadera:autoform-googleplace  1.0.7+ Google Places Autocomplete input (without map). Returns an object with formatted address components
matb33:collection-hooks          0.8.4  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteor-base                      1.0.4  Packages that every Meteor app needs
meteorhacks:kadira               2.30.2  Performance Monitoring for Meteor
mobile-experience                1.0.4  Packages for a great mobile user experience
momentjs:moment                  2.15.2  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                            1.1.13  Adaptor for using MongoDB and Minimongo over DDP
natestrauser:select2             4.0.3  Select2 is a jQuery based replacement for select boxes.
ostrio:autoform-files            1.0.7+ File upload for AutoForm using ostrio:files
ostrio:files                     1.7.5  Upload files via DDP, HTTP and WebRTC/DC. To server FS, AWS, GridFS, DropBox or Google Drive.
session                          1.1.6  Session variable
shell-server                     0.2.1  Server-side component of the `meteor shell` command.
standard-minifier-css            1.2.1* Standard css minifier used with Meteor apps by default.
standard-minifier-js             1.2.0_1  Standard javascript minifiers used with Meteor apps by default.
tracker                          1.1.0  Dependency tracker to allow reactive callbacks
u2622:persistent-session         0.4.4  Persistently store Session data on the client
useraccounts:bootstrap           1.14.2  Accounts Templates styled for Twitter Bootstrap.
useraccounts:flow-routing        1.14.2  UserAccounts package providing routes configuration capability via kadira:flow-router.
webtempest:animate               0.1.9  Easily perform CSS animations and transitions in Meteor
zeroasterisk:auditlog            0.0.3+ Simple, generic, extensible audit logging on collection insert, update, upsert, remove

```
